# Copyright 2017 The Openstack-Helm Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: set node_pass
  set_fact:
    node_pass: false

- name: dump the stats file
  shell: grep "{{ hostvars[inventory_hostname].ansible_hostname }}.*Ready" /tmp/nodestat
  register: statsinfo
  ignore_errors: yes

- debug:
    msg: "{{ statsinfo }}"

- name: evaluate node pass
  set_fact:
    node_pass: true
  when: statsinfo.rc  == 0

- name: print node_pass
  debug:
    msg: "{{ node_pass }}"

- name: check if docker deploy is needed
  raw: which docker
  register: need_docker
  ignore_errors: True

- name: centos | moving systemd unit into place
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' ) and ( need_docker | failed )
  template:
    src: centos-docker.service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0640

- name: fedora | moving systemd unit into place
  when: ( ansible_distribution == 'Fedora' ) and ( need_docker | failed )
  template:
    src: fedora-docker.service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0640

- name: ubuntu | moving systemd unit into place
  when: ( ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' ) and ( need_docker | failed )
  template:
    src: ubuntu-docker.service.j2
    dest: /etc/systemd/system/docker.service
    mode: 0640

# NOTE: (lamt) Setting up the proxy before installing docker
- name: ensure docker.service.d directory exists
  when: proxy.http is defined and (proxy.http | trim != "")
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory

- name: proxy | moving proxy systemd unit into place
  when: ( need_docker | failed ) and ( proxy.http is defined and (proxy.http | trim != "") )
  template:
    src: http-proxy.conf.j2
    dest: /etc/systemd/system/docker.service.d/http-proxy.conf
    mode: 0640

- name: centos | add docker-ce repository
  when: ( ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux' ) and ( need_docker | failed )
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: fedora | add docker-ce repository
  when: ( ansible_distribution == 'Fedora' ) and ( need_docker | failed )
  get_url:
    url: https://download.docker.com/linux/fedora/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: deploy docker packages
  when: need_docker | failed
  include_role:
    name: deploy-package
    tasks_from: dist
  vars:
    packages:
      deb:
        - docker.io
      rpm:
        - docker-ce

- name: check if docker insecure registry is defined
  set_fact:
    docker_insecure_registries: "{% if docker.insecure_registries is defined %}\"{{ '\", \"'.join(docker.insecure_registries) }}\"{% endif %}"

- name: moving daemon.json file to /etc/docker/daemon.json
  when: docker_insecure_registries is defined
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: 0640

- name: restarting docker
  systemd:
    state: restarted
    daemon_reload: yes
    name: docker
  when: node_pass == false

- name: login to private_registries
  when: docker.private_registries is defined
  become: true
  become_user: root
  command: docker login --username {{ item.username }} --password {{ item.password }} {{ item.name }}
  with_items: "{{ docker.private_registries }}"

- include: deploy-ansible-docker-support.yaml
