
- name: check /etc/host file exists
  stat:
    path: /etc/hosts
  register: file_st

- name: Remove duplicate host entrie(s)
  lineinfile:
    dest: /etc/hosts
    regexp: "^[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3}.[0-9]{1,3} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
    state: absent
  with_items: "{{ groups['all'] }}"
  when: item != inventory_hostname

- name: add host entry to /etc/hosts file
  lineinfile: dest=/etc/hosts line="{{ hostvars[item]['ansible_host'] }} {{ hostvars[item]['ansible_fqdn'] }} {{ hostvars[item]['ansible_hostname'] }}"
  with_items: "{{ groups['all'] }}"
  when: file_st.stat.exists == true and item != inventory_hostname
